on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-20.04
    name: First test with my own action with act
    steps:
      - uses: actions/checkout@v2
        with:
          path: "rancher-cli"
      - name: Rancher tests
        uses: ./
        id: rancher
        with:
          uri: 'https://rancher.rancher'
          token: 'token-ashoiha:wjaw9a7w0a7waoeaghea'
          context: 'c-d5sasa:asmasa89s-a8sa'
          command: rancher kubectl get pods -n orders
      - name: Test output
        run: |
          echo "context ${{ steps.rancher.outputs.context_name }}"
          echo "command ${{ steps.rancher.outputs.command_name }}"

